{
  "author_association": "MEMBER",
  "created_at": "2017-01-30T08:57:55Z",
  "assignee": null,
  "locked": false,
  "user": {
    "starred_url": "https://api.github.com/users/AlexDaniel/starred{/owner}{/repo}",
    "html_url": "https://github.com/AlexDaniel",
    "gravatar_id": "",
    "login": "AlexDaniel",
    "site_admin": false,
    "type": "User",
    "gists_url": "https://api.github.com/users/AlexDaniel/gists{/gist_id}",
    "id": 5507503,
    "events_url": "https://api.github.com/users/AlexDaniel/events{/privacy}",
    "following_url": "https://api.github.com/users/AlexDaniel/following{/other_user}",
    "url": "https://api.github.com/users/AlexDaniel",
    "avatar_url": "https://avatars3.githubusercontent.com/u/5507503?v=4",
    "node_id": "MDQ6VXNlcjU1MDc1MDM=",
    "received_events_url": "https://api.github.com/users/AlexDaniel/received_events",
    "repos_url": "https://api.github.com/users/AlexDaniel/repos",
    "organizations_url": "https://api.github.com/users/AlexDaniel/orgs",
    "subscriptions_url": "https://api.github.com/users/AlexDaniel/subscriptions",
    "followers_url": "https://api.github.com/users/AlexDaniel/followers"
  },
  "updated_at": "2017-01-31T01:37:36Z",
  "html_url": "https://github.com/perl6/doc/issues/1170",
  "comments_url": "https://api.github.com/repos/perl6/doc/issues/1170/comments",
  "labels_url": "https://api.github.com/repos/perl6/doc/issues/1170/labels{/name}",
  "body": "https://docs.perl6.org/routine/throw\r\n\r\n```perl6\r\n    my $exception = X::AdHoc.new; # Totally fine\r\n    try $exception.throw;             # Throws\r\n    if ($!) { #`( some handling ) };                   # Suppress the exception in a\r\n```\r\n\r\n“Suppress the exception in a” ? Something is missing, not sure what exactly.",
  "repository_url": "https://api.github.com/repos/perl6/doc",
  "closed_at": "2017-01-31T01:37:35Z",
  "comments": 5,
  "assignees": [
    
  ],
  "milestone": null,
  "state": "closed",
  "id": 203954853,
  "closed_by": {
    "starred_url": "https://api.github.com/users/Altai-man/starred{/owner}{/repo}",
    "html_url": "https://github.com/Altai-man",
    "gravatar_id": "",
    "login": "Altai-man",
    "site_admin": false,
    "type": "User",
    "gists_url": "https://api.github.com/users/Altai-man/gists{/gist_id}",
    "id": 5764435,
    "events_url": "https://api.github.com/users/Altai-man/events{/privacy}",
    "following_url": "https://api.github.com/users/Altai-man/following{/other_user}",
    "url": "https://api.github.com/users/Altai-man",
    "avatar_url": "https://avatars1.githubusercontent.com/u/5764435?v=4",
    "node_id": "MDQ6VXNlcjU3NjQ0MzU=",
    "received_events_url": "https://api.github.com/users/Altai-man/received_events",
    "repos_url": "https://api.github.com/users/Altai-man/repos",
    "organizations_url": "https://api.github.com/users/Altai-man/orgs",
    "subscriptions_url": "https://api.github.com/users/Altai-man/subscriptions",
    "followers_url": "https://api.github.com/users/Altai-man/followers"
  },
  "labels": [
    {
      "default": false,
      "id": 244843225,
      "color": "5DE0FA",
      "url": "https://api.github.com/repos/perl6/doc/labels/docs",
      "node_id": "MDU6TGFiZWwyNDQ4NDMyMjU=",
      "name": "docs"
    }
  ],
  "number": 1170,
  "node_id": "MDU6SXNzdWUyMDM5NTQ4NTM=",
  "events_url": "https://api.github.com/repos/perl6/doc/issues/1170/events",
  "url": "https://api.github.com/repos/perl6/doc/issues/1170",
  "title": "Comments in a snippet about ｢throw｣ are weird"
}